# Docker Compose Override para Desenvolvimento
# Este arquivo é usado para configurações específicas de desenvolvimento

services:
  homeassistant:
    # Configurações de desenvolvimento
    environment:
      - TZ=Europe/Lisbon
      - PYTHONUNBUFFERED=1
    volumes:
      # Adicionar volume para desenvolvimento
      - ./dev:/config/dev
    # Configurações de rede para desenvolvimento
    ports:
      - "8123:8123"
      - "4357:4357"  # Porta para debug

  # Configurações de desenvolvimento para outros serviços
  mosquitto:
    ports:
      - "1883:1883"
      - "9001:9001"

  grafana:
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource

  influxdb:
    ports:
      - "8086:8086"

  zigbee2mqtt:
    ports:
      - "8080:8080"
